[package]
name = "raytrace"
version = "0.1.0"
authors = ["Daniel Rivas Perez <drivas12@googlemail.com>"]
edition = "2018"

[dependencies]
rayon = "1.0"
rand = "0.6"
image = "0.21"
wasm-bindgen = "0.2.49"
cfg-if = "0.1.9"
